---
apiVersion: "wso2.com/v1alpha2"
kind: "Integration"
metadata:
  name: "demo1"
spec:
  image: "virajhasith/cicdwso2mi:1.0.0-SNAPSHOT"
  deploySpec:
    minReplicas: 1
    livenessProbe:
      tcpSocket:
        port: 8290
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /healthz
        port: 9201
      initialDelaySeconds: 30
      periodSeconds: 10